# Site info
title: 'Antonio Vázquez Blanco'
url: http://antoniovazquezblanco.github.io/

# Author
author:
  name: 'Antonio Vázquez Blanco'
  email: 'antoniovazquezblanco@gmail.com'

# Dependencies
highlighter: pygments
markdown: redcarpet

# Pagination
paginate: 6
paginate_path: "blog/page:num"

# Navigation
navigation:
- title: Home
  url: /
- title: Blog
  url: /blog/
