# URL settings
url: "https://antoniovazquezblanco.github.io"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# File exclusion
exclude:
- README.md
- Gemfile.lock
- Gemfile

# Seo settings
title: Antón

tagline: Hacking, Reversing, Programming, HAM Radio...

description: Trying to improve and understand as much as possible about hacking, reverse engineering, programming, HAM radio, hardware and more.

author:
  name: Antonio Vázquez Blanco
  url: https://antoniovazquezblanco.github.io/

social:
  name: Antonio Vázquez Blanco
  links:
    - https://twitter.com/antonvblanco
    - https://www.linkedin.com/in/antoniovazquezblanco/
    - https://github.com/antoniovazquezblanco
