title: Mental crashdumps

author:
  name: Antonio Vázquez Blanco
  email: antoniovazquezblanco@gmail.com

description: >-
  Here I pretend to (not very often) write down some of my findings,
  ideas and other (hopefully) useful information that I feel may be
  worth sharing.

remote_theme: antoniovazquezblanco/jekyll-theme-ascii

header_pages:
 - index.md
 - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-redirect-from

mastodon_comments:
  host: mastodon.social
